// lib/caCities.ts
export type CACity = { city: string; region: string; country: "Canada" };

export const CA_CITIES: CACity[] = [
  { city: "Toronto", region: "ON", country: "Canada" },
  { city: "Montréal", region: "QC", country: "Canada" },
  { city: "Vancouver", region: "BC", country: "Canada" },
  { city: "Calgary", region: "AB", country: "Canada" },
  { city: "Edmonton", region: "AB", country: "Canada" },
  { city: "Ottawa", region: "ON", country: "Canada" },
  { city: "Winnipeg", region: "MB", country: "Canada" },
  { city: "Québec City", region: "QC", country: "Canada" },
  { city: "Hamilton", region: "ON", country: "Canada" },
  { city: "Kitchener–Waterloo", region: "ON", country: "Canada" },
  { city: "London", region: "ON", country: "Canada" },
  { city: "Halifax", region: "NS", country: "Canada" },
  { city: "Victoria", region: "BC", country: "Canada" },
  { city: "Saskatoon", region: "SK", country: "Canada" },
  { city: "Regina", region: "SK", country: "Canada" },
  { city: "St. John's", region: "NL", country: "Canada" },
  { city: "Mississauga", region: "ON", country: "Canada" },
  { city: "Brampton", region: "ON", country: "Canada" },
  { city: "Surrey", region: "BC", country: "Canada" },
  { city: "Laval", region: "QC", country: "Canada" },
  { city: "Gatineau", region: "QC", country: "Canada" },
  { city: "Longueuil", region: "QC", country: "Canada" },
  { city: "Burnaby", region: "BC", country: "Canada" },
  { city: "Richmond", region: "BC", country: "Canada" },
  { city: "Oakville", region: "ON", country: "Canada" },
  { city: "Burlington", region: "ON", country: "Canada" },
  { city: "Oshawa", region: "ON", country: "Canada" },
];
